In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Location               20000 non-null  object
 1   Cross_Street           3448 non-null   object
 2   Latitude               20000 non-null  float64
 3   Longitude              20000 non-null  float64
 4   Date_Reported          20000 non-null  object
 5   Date_Occurred          20000 non-null  object
 6   Time_Occurred          20000 non-null  float64
 7   Area_ID                20000 non-null  float64
 8   Area_Name              20000 non-null  object
 9   Reporting_District_no  20000 non-null  float64
 10  Part 1-2               20000 non-null  float64
 11  Modus_Operandi         17259 non-null  object
 12  Victim_Age             20000 non-null  float64
 13  Victim_Sex             17376 non-null  object
 14  Victim_Descent         17376 non-null  object
 15  Premise_Code           20000 non-null  float64
 16  Premise_Description    19995 non-null  object
 17  Weapon_Used_Code       7335 non-null   float64
 18  Weapon_Description     7335 non-null   object
 19  Status                 20000 non-null  object
 20  Status_Description     20000 non-null  object
 21  Crime_Category         20000 non-null  object
dtypes: float64(9), object(13)
memory usage: 3.4+ MB

In [3]:
train.head(10)

,Location,Cross_Street,Latitude,Longitude,Date_Reported,Date_Occurred,Time_Occurred,Area_ID,Area_Name,Reporting_District_no,...,Victim_Age,Victim_Sex,Victim_Descent,Premise_Code,Premise_Description,Weapon_Used_Code,Weapon_Description,Status,Status_Description,Crime_Category
0,4500 CARPENTER AV,NaN,34.1522,-118.3910,03/09/2020 12:00:00 AM,03/06/2020 12:00:00 AM,1800.0,15.0,N Hollywood,1563.0,...,75.0,M,W,101.0,STREET,NaN,NaN,IC,Invest Cont,Property Crimes
1,45TH ST,ALAMEDA ST,34.0028,-118.2391,02/27/2020 12:00:00 AM,02/27/2020 12:00:00 AM,1345.0,13.0,Newton,1367.0,...,41.0,M,H,216.0,SWAP MEET,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,Property Crimes
2,600 E MARTIN LUTHER KING JR BL,NaN,34.0111,-118.2653,08/21/2020 12:00:00 AM,08/21/2020 12:00:00 AM,605.0,13.0,Newton,1343.0,...,67.0,M,B,501.0,SINGLE FAMILY DWELLING,NaN,NaN,IC,Invest Cont,Property Crimes
3,14900 ORO GRANDE ST,NaN,34.2953,-118.4590,11/08/2020 12:00:00 AM,11/06/2020 12:00:00 AM,1800.0,19.0,Mission,1924.0,...,61.0,M,H,101.0,STREET,NaN,NaN,IC,Invest Cont,Property Crimes
4,7100 S VERMONT AV,NaN,33.9787,-118.2918,02/25/2020 12:00:00 AM,02/25/2020 12:00:00 AM,1130.0,12.0,77th Street,1245.0,...,0.0,X,X,401.0,MINI-MART,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,Property Crimes
5,300 N AVENUE 57,NaN,34.1127,-118.1942,01/10/2020 12:00:00 AM,01/10/2020 12:00:00 AM,256.0,11.0,Northeast,1118.0,...,50.0,M,H,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",AO,Adult Other,Violent Crimes
6,1600 N SOTO ST,NaN,34.0623,-118.1980,08/17/2020 12:00:00 AM,08/17/2020 12:00:00 AM,1840.0,4.0,Hollenbeck,448.0,...,0.0,X,X,202.0,LIQUOR STORE,NaN,NaN,IC,Invest Cont,Property Crimes
7,12600 BRADDOCK DR,NaN,33.9864,-118.4239,10/07/2021 12:00:00 AM,03/19/2020 12:00:00 AM,1100.0,14.0,Pacific,1455.0,...,68.0,F,W,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",NaN,NaN,IC,Invest Cont,Property Crimes
8,5500 COLDWATER CA AV,NaN,34.1781,-118.4179,01/28/2020 12:00:00 AM,01/26/2020 12:00:00 AM,1600.0,9.0,Van Nuys,939.0,...,0.0,NaN,NaN,104.0,DRIVEWAY,NaN,NaN,IC,Invest Cont,Property Crimes
9,11500 AVIATION BL,NaN,33.9298,-118.3784,07/07/2020 12:00:00 AM,07/07/2020 12:00:00 AM,445.0,14.0,Pacific,1499.0,...,22.0,F,H,108.0,PARKING LOT,NaN,NaN,AA,Adult Arrest,Property Crimes

In [4]:
train = train.drop(columns=['Location', 'Cross_Street', 'Date_Reported', 'Date_Occurred', 'Area_Name', 'Premise_Description', 'Weapon_Description', 'Status_Description'])
test = test.drop(columns=['Location', 'Cross_Street', 'Date_Reported', 'Date_Occurred', 'Area_Name', 'Premise_Description', 'Weapon_Description', 'Status_Description'])

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Latitude               20000 non-null  float64
 1   Longitude              20000 non-null  float64
 2   Time_Occurred          20000 non-null  float64
 3   Area_ID                20000 non-null  float64
 4   Reporting_District_no  20000 non-null  float64
 5   Part 1-2               20000 non-null  float64
 6   Modus_Operandi         17259 non-null  object
 7   Victim_Age             20000 non-null  float64
 8   Victim_Sex             17376 non-null  object
 9   Victim_Descent         17376 non-null  object
 10  Premise_Code           20000 non-null  float64
 11  Weapon_Used_Code       7335 non-null   float64
 12  Status                 20000 non-null  object
 13  Crime_Category         20000 non-null  object
dtypes: float64(9), object(5)
memory usage: 2.1+ MB

In [6]:
train['Victim_Sex'].value_counts()

Victim_Sex
M    8538
F    7176
X    1660
H       2
Name: count, dtype: int64

In [7]:
train['Victim_Descent'].value_counts()

Victim_Descent
H    6143
W    4245
B    2881
X    1849
O    1603
A     427
K      83
C      51
F      48
J      16
I      11
V       8
P       4
Z       3
U       2
D       1
G       1
Name: count, dtype: int64

In [8]:
train['Modus_Operandi'].value_counts()

Modus_Operandi
0344                                       826
0329                                       583
1501                                       187
0329 1300                                  135
0325                                       127
                                          ...
1609 0329 1307 0344                          1
0344 2050 0910 2034                          1
0400 2000 0913                               1
1822 0342 0910 2049 2051 0305 0444 0344      1
1202 2038 0913 0602 1242 0553                1
Name: count, Length: 10489, dtype: int64

In [9]:
train['Crime_Category'].value_counts()

Crime_Category
Property Crimes                  11666
Violent Crimes                    4767
Crimes against Public Order       1808
Fraud and White-Collar Crimes     1355
Crimes against Persons             225
Other Crimes                       179
Name: count, dtype: int64

In [10]:
# Label encoding
label_encode = LabelEncoder()
train['Victim_Sex'] = label_encode.fit_transform(train['Victim_Sex'])
train['Victim_Descent'] = label_encode.fit_transform(train['Victim_Descent'])
train['Status'] = label_encode.fit_transform(train['Status'])

test['Victim_Sex'] = label_encode.fit_transform(test['Victim_Sex'])
test['Victim_Descent'] = label_encode.fit_transform(test['Victim_Descent'])
test['Status'] = label_encode.fit_transform(test['Status'])

y_train = train['Crime_Category']

In [11]:
train['Weapon_Used_Code'] = train['Weapon_Used_Code'].fillna(0)
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Latitude               20000 non-null  float64
 1   Longitude              20000 non-null  float64
 2   Time_Occurred          20000 non-null  float64
 3   Area_ID                20000 non-null  float64
 4   Reporting_District_no  20000 non-null  float64
 5   Part 1-2               20000 non-null  float64
 6   Modus_Operandi         17259 non-null  object
 7   Victim_Age             20000 non-null  float64
 8   Victim_Sex             20000 non-null  int32
 9   Victim_Descent         20000 non-null  int32
 10  Premise_Code           20000 non-null  float64
 11  Weapon_Used_Code       20000 non-null  float64
 12  Status                 20000 non-null  int32
 13  Crime_Category         20000 non-null  object
dtypes: float64(9), int32(3), object(2)
memory usage: 1.9+ MB

In [12]:
test['Weapon_Used_Code'] = test['Weapon_Used_Code'].fillna(0)
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Latitude               5000 non-null   float64
 1   Longitude              5000 non-null   float64
 2   Time_Occurred          5000 non-null   float64
 3   Area_ID                5000 non-null   float64
 4   Reporting_District_no  5000 non-null   float64
 5   Part 1-2               5000 non-null   float64
 6   Modus_Operandi         4316 non-null   object
 7   Victim_Age             5000 non-null   float64
 8   Victim_Sex             5000 non-null   int32
 9   Victim_Descent         5000 non-null   int32
 10  Premise_Code           5000 non-null   float64
 11  Weapon_Used_Code       5000 non-null   float64
 12  Status                 5000 non-null   int32
dtypes: float64(9), int32(3), object(1)
memory usage: 449.3+ KB

In [13]:
train['Modus_Operandi'] = train['Modus_Operandi'].astype(str)
train['Modus_Operandi'] = train['Modus_Operandi'].fillna('').apply(lambda x: x.split())

test['Modus_Operandi'] = test['Modus_Operandi'].astype(str)
test['Modus_Operandi'] = test['Modus_Operandi'].fillna('').apply(lambda x: x.split())

from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()

modus_encoded = mlb.fit_transform(train['Modus_Operandi'])
modus_encoded_train = pd.DataFrame(modus_encoded, columns=mlb.classes_, index=train.index)
train = train.join(modus_encoded_train).drop(columns=['Modus_Operandi'])

modus_encoded = mlb.fit_transform(test['Modus_Operandi'])
modus_encoded_test = pd.DataFrame(modus_encoded, columns=mlb.classes_, index=test.index)
test = test.join(modus_encoded_test).drop(columns=['Modus_Operandi'])

train

,Latitude,Longitude,Time_Occurred,Area_ID,Reporting_District_no,Part 1-2,Victim_Age,Victim_Sex,Victim_Descent,Premise_Code,...,2157,2201,2204,2303,2304,3003,3004,4025,9999,nan
0,34.1522,-118.3910,1800.0,15.0,1563.0,1.0,75.0,2,14,101.0,...,0,0,0,0,0,0,0,0,0,0
1,34.0028,-118.2391,1345.0,13.0,1367.0,1.0,41.0,2,6,216.0,...,0,0,0,0,0,0,0,0,0,0
2,34.0111,-118.2653,605.0,13.0,1343.0,2.0,67.0,2,1,501.0,...,0,0,0,0,0,0,0,0,0,0
3,34.2953,-118.4590,1800.0,19.0,1924.0,1.0,61.0,2,6,101.0,...,0,0,0,0,0,0,0,0,0,0
4,33.9787,-118.2918,1130.0,12.0,1245.0,1.0,0.0,3,15,401.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,34.0334,-118.3523,700.0,3.0,303.0,2.0,51.0,2,6,501.0,...,0,0,0,0,0,0,0,0,0,0
19996,34.2212,-118.5011,259.0,10.0,1008.0,1.0,0.0,2,14,301.0,...,0,0,0,0,0,0,0,0,0,0
19997,34.0571,-118.3815,1400.0,8.0,849.0,1.0,42.0,2,6,102.0,...,0,0,0,0,0,0,0,0,0,0
19998,33.7451,-118.2835,600.0,5.0,558.0,2.0,76.0,0,6,501.0,...,0,0,0,0,0,0,0,0,0,0
19999,34.0037,-118.3034,1800.0,3.0,397.0,1.0,0.0,4,17,101.0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
for col in train.columns:
    if col not in test.columns:
        test[col] = 0
test = test[train.columns]
test

C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0
C:\Users\Huynh Han Dong\AppData\Local\Temp\ipykernel_4896\3622453157.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test[col] = 0

,Latitude,Longitude,Time_Occurred,Area_ID,Reporting_District_no,Part 1-2,Victim_Age,Victim_Sex,Victim_Descent,Premise_Code,...,2157,2201,2204,2303,2304,3003,3004,4025,9999,nan
0,34.0128,-118.3045,2000.0,3.0,376.0,2.0,28.0,0,5,501.0,...,0,0,0,0,0,0,0,0,0,0
1,34.0726,-118.3029,1700.0,20.0,2014.0,1.0,26.0,2,1,502.0,...,0,0,0,0,0,0,0,0,0,0
2,33.9348,-118.2695,900.0,18.0,1844.0,2.0,62.0,0,1,721.0,...,0,0,0,0,0,0,0,0,0,0
3,34.0497,-118.3442,2200.0,7.0,765.0,1.0,0.0,4,16,108.0,...,0,0,0,0,0,0,0,0,0,1
4,34.1611,-118.3704,130.0,15.0,1555.0,2.0,37.0,0,13,501.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,34.0409,-118.3408,2100.0,7.0,775.0,1.0,0.0,4,16,101.0,...,0,0,0,0,0,0,0,0,0,1
4996,34.0347,-118.2253,1530.0,4.0,471.0,1.0,0.0,3,14,116.0,...,0,0,0,0,0,0,0,0,0,0
4997,34.2392,-118.4698,2100.0,19.0,1961.0,2.0,38.0,2,5,101.0,...,0,0,0,0,0,0,0,0,0,0
4998,34.0453,-118.2443,2335.0,1.0,147.0,2.0,41.0,2,1,502.0,...,0,0,0,0,0,0,0,0,0,0
4999,33.9438,-118.2695,320.0,18.0,1823.0,2.0,49.0,2,1,122.0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
# Modeling
x = train.drop(columns='Crime_Category')
y = train['Crime_Category']
model = (RandomForestClassifier(random_state=42))  
model.fit(x,y)
prediction = model.predict(test.drop(columns='Crime_Category'))

In [ ]:
submission = pd.DataFrame(columns=["ID", "Crime_Category"])
submission['Crime_Category'] = prediction
submission['ID'] = submission['Crime_Category'].index + 1
submission.to_csv('crime-categories-forecasting.csv', index=False)
submission

        ID                 Crime_Category
0        1                 Violent Crimes
1        2                Property Crimes
2        3  Fraud and White-Collar Crimes
3        4                Property Crimes
4        5    Crimes against Public Order
...    ...                            ...
4995  4996                Property Crimes
4996  4997                Property Crimes
4997  4998                 Violent Crimes
4998  4999                 Violent Crimes
4999  5000                Property Crimes

[5000 rows x 2 columns]